version: '3.4'
services:
  netbox:
    ports:
      - 8765:8767
    volumes:
      - ./netbox/config:/etc/netbox/config:ro
      - ./netbox/media:/opt/netbox/netbox/media
      - ./netbox/reports:/opt/netbox/netbox/reports
      - ./netbox/scripts:/opt/netbox/netbox/scripts
    healthcheck:
      retries: 15

  netbox-worker:
    volumes:
      - ./netbox/config:/etc/netbox/config:ro
      - ./netbox/media:/opt/netbox/netbox/media
      - ./netbox/reports:/opt/netbox/netbox/reports
      - ./netbox/scripts:/opt/netbox/netbox/scripts

  netbox-housekeeping:
    volumes:
      - ./netbox/config:/etc/netbox/config:ro
      - ./netbox/media:/opt/netbox/netbox/media
      - ./netbox/reports:/opt/netbox/netbox/reports
      - ./netbox/scripts:/opt/netbox/netbox/scripts
